{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n  +'1'\n  -1", "trace": "self = <test_allure.test_feature_story.TestLogin object at 0x0000021C33774820>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"点击用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\nE             +'1'\nE             -1\n\ntest_feature_story.py:51: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1629423321215, "stop": 1629423321215}, {"name": "点击密码", "status": "passed", "start": 1629423321215, "stop": 1629423321215}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n  +'1'\n  -1\n", "trace": "  File \"C:\\Users\\Administrator\\PycharmProjects\\TestPytest\\test_allure\\test_feature_story.py\", line 51, in test_login_failure\n    assert '1' == 1\n"}, "start": 1629423321215, "stop": 1629423321215}], "start": 1629423321215, "stop": 1629423321215, "uuid": "c089dba9-ac05-48b4-93b4-fb0c68834731", "historyId": "a58c5550e5c40eb80abda2e84e87077a", "testCaseId": "a0fb827149424dbc77d431148fe9f888", "fullName": "test_feature_story.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-GRKQKVO"}, {"name": "thread", "value": "37372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}